<?php

/**
 * @file
 * Site configuration Form customizations for ax_json_api module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function ax_json_api_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  $config = \Drupal::config('system.site');
  $jsonapikey = $config->get('siteapikey');

  // If Site API key is not null, Button value will be "Update configuration".
  $apikeyvalue = $jsonapikey;
  $submitbtnvalue = t('Update configuration');

  // If API key is not null then Submit button value will be
  // 'Save configuration'.
  if ($jsonapikey == NULL) {
    $apikeyvalue = t('No API key yet');
    $submitbtnvalue = t('Save configuration');
  }

  if ($form_id == 'system_site_information_settings') {
    $form['siteapikey'] = [
      '#type' => 'textfield',
      '#title' => t('Site API Key'),
      '#description' => t('API key for JSON file'),
      '#default_value' => $apikeyvalue,
    ];
    $form['actions']['submit']['#value'] = $submitbtnvalue;
    $form['actions']['submit']['#submit'][] = 'ax_json_api_siteapikey_submit';
  }
}

/**
 * Implements custom submit button handler.
 */
function ax_json_api_siteapikey_submit($form, FormStateInterface $form_state) {
  $config = \Drupal::service('config.factory')->getEditable('system.site');
  $siteapikey = $form_state->getValue('siteapikey');
  $config->set('siteapikey', NULL)->save();

  if ($siteapikey != NULL && $siteapikey != t('No API key yet')) {
    $config->set('siteapikey', $siteapikey)->save();
    \Drupal::messenger()->addStatus(t('Site API Key has been saved with '.$siteapikey));
  }
}
